sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Apparently six must be installed first, otherwise setup.py will be unhappy
install:
  - pip install --upgrade six
  - pip install --upgrade -r requirements_dev.txt
script: py.test --cov .
after_success: coveralls
