dist: xenial
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade -r requirements_dev.txt
  # Black only runs under Python >= 3.6
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install black==19.10b0; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black --check *.py */; fi
  # isort 5 only runs under Python >= 3.6
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then isort --check-only --recursive *.py */; fi
  - flake8
  - py.test --cov .
after_success: coveralls
